
---

- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ['packages']

- name: Installation and configuration of useful tools and programs
  apt: state=latest pkg={{ item }}
  with_items: "{{ common_tools }}"
  when: ansible_os_family == 'Debian'
  tags: ['packages']

- name: Install vim editor
  apt: pkg={{ item }} state=latest
  with_items:
      - vim-nox
  tags: ['packages']

- name: Create customized vim configuration file
  copy: src=vimrc.local dest=/etc/vim/vimrc.local

