
---

- name: Installation and configuration of useful tools and programs
  apt: pkg={{ item }} state=latest
  with_items:
      - htop
      - lsof
      - multitail
  tags: ['packages']

- name: Install vim editor
  apt: pkg={{ item }} state=latest
  with_items:
      - vim-nox
  tags: ['packages']

- name: Create customized vim configuration file
  copy: src=vimrc.local dest=/etc/vim/vimrc.local

